# Generated by Django 2.2 on 2021-05-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic = False
    dependencies = [
        ('login_app', '0002_auto_20210515_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to='login_app.User')),
                ('users_joined', models.ManyToManyField(related_name='trips_joined', to='login_app.User')),
            ],
        ),
    ]
