# Generated by Django 2.2 on 2021-05-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210515_1856'),
        ('travel_app', '0001_initial'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
